## 3.A. Numpy

In [62]:
import numpy as np

In [63]:
# arange
# np.arange([start,] stop[,step,], dtype=None)

print(np.arange(10))
print(np.arange(1, 10))
print(np.arange(1, 10, 2)) # using print will remove the ,
print(np.arange(1, 10, 0.5))
np.arange(1, 10, dtype='float64')

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [64]:
# Examining the ndarray

arr = np.arange(1,10)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize) # in 64bit machines, it takes 8 bits to be store an integer
# If I save this as `dtype='int32'` it will take 4 bits

1
(9,)
9
int64
8


In [65]:
# Memory usage calculation
arr.size * arr.itemsize
# array size is 9 integers and and in 64 bit machine it takes 8 bits to store each integer
# Therefore, total 72 bits of memory used to store an array of size 9

72

**Why used numpy**<br/>
Numpy does all calculations in 2-D or 3-D arrays in vectorized manners. Thus we get faster output w.r.t list based operations

In [66]:
%timeit list1 = range(1,1000)

347 ns ± 7.96 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [67]:
%timeit list1 = np.arange(1,1000)

1.65 µs ± 15 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


• In case of numpy we had to run 100k loops while in list operation we had to use 1M loops<br/>

In [68]:
# List to Array # 1-D
list_1D = [1,2,3,4,5]
print(np.asarray(list_1D))

# List to Array # 2-D
list_2D = [[1,2,3], [4,5,6]]
print(np.asarray(list_2D))

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [69]:
# Generate ZEROS
# zeros(shape, dtype=float, order='C')

listzeros = np.zeros((3,4), dtype='int64')
listzeros

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [70]:
# Linspace
# np.linspace(start, stop, num=50, endpoint=True, restep=False)

print(np.linspace(1,4, num=4))
print(np.linspace(1,4, num=8))
print(np.linspace(1,4, num=8, endpoint=False))

[1. 2. 3. 4.]
[1.         1.42857143 1.85714286 2.28571429 2.71428571 3.14285714
 3.57142857 4.        ]
[1.    1.375 1.75  2.125 2.5   2.875 3.25  3.625]


`num` is the number of equally spaced elements generated between `start` and `stop`

In [71]:
# random generation
np.random.random((3,4))

array([[0.18987066, 0.99742505, 0.23253815, 0.54833447],
       [0.61088724, 0.79138593, 0.3271145 , 0.84123764],
       [0.04079631, 0.09785942, 0.15973928, 0.30531213]])

In [72]:
rarr = np.random.random((3,4))
print(rarr)
print('-'*45)
print(np.max(rarr, axis = 0)) # along columns
print('-'*45)
print(np.max(rarr, axis = 1)) # along rows
print('-'*45)

[[0.35440805 0.42421647 0.05080027 0.88697123]
 [0.52095557 0.63109658 0.46478828 0.00988048]
 [0.0874302  0.39247127 0.4926922  0.01711404]]
---------------------------------------------
[0.52095557 0.63109658 0.4926922  0.88697123]
---------------------------------------------
[0.88697123 0.63109658 0.4926922 ]
---------------------------------------------


In [73]:
rarr = np.random.random((3,4))
print(rarr)
print('-'*45)
print(np.min(rarr, axis = 0)) # along columns
print('-'*45)
print(np.min(rarr, axis = 1)) # along rows
print('-'*45)

[[0.37259295 0.04893875 0.50411889 0.98204074]
 [0.16247397 0.19345832 0.5848142  0.61282767]
 [0.73369729 0.68675832 0.3076062  0.71140855]]
---------------------------------------------
[0.16247397 0.04893875 0.3076062  0.61282767]
---------------------------------------------
[0.04893875 0.16247397 0.3076062 ]
---------------------------------------------


In [74]:
rarr = np.random.random((3,4))
print(rarr)
print('-'*45)
print(np.median(rarr, axis = 0)) # along columns
print('-'*45)
print(np.median(rarr, axis = 1)) # along rows
print('-'*45)

[[8.50608140e-01 8.78216303e-01 1.76025645e-01 1.83761333e-01]
 [8.67653115e-01 8.42053995e-01 8.83646622e-01 6.26247049e-01]
 [4.53257147e-01 4.39472509e-01 8.67682107e-01 1.74925085e-04]]
---------------------------------------------
[0.85060814 0.842054   0.86768211 0.18376133]
---------------------------------------------
[0.51718474 0.85485355 0.44636483]
---------------------------------------------


In [76]:
# Reshaping
# np.reshape(a, newshape, order = 'C')

rarr = np.random.random((3,4)) # 3rows and 4 columns
print(rarr)
print('-'*45)
new_arr = np.reshape(rarr, (12,)) # 1-D array
print(new_arr)
print('-'*70)
new_arr = np.reshape(rarr, (12,1)) # 12 rows and 1 column
print(new_arr)

[[0.88352891 0.20584843 0.70841732 0.45365756]
 [0.1915833  0.73982752 0.84072891 0.77818396]
 [0.40581099 0.64279928 0.57658682 0.26354046]]
---------------------------------------------
[0.88352891 0.20584843 0.70841732 0.45365756 0.1915833  0.73982752
 0.84072891 0.77818396 0.40581099 0.64279928 0.57658682 0.26354046]
----------------------------------------------------------------------
[[0.88352891]
 [0.20584843]
 [0.70841732]
 [0.45365756]
 [0.1915833 ]
 [0.73982752]
 [0.84072891]
 [0.77818396]
 [0.40581099]
 [0.64279928]
 [0.57658682]
 [0.26354046]]


In [77]:
# slicing

rarr = np.random.random((4,5))
print(rarr)
print('-'*55)
print(rarr[:,:]) # copies everything- all rows and columns
print('-'*55)
print(rarr[1:3,:]) # copy only 2nd and 3rd row and all columns
print('-'*55)
print(rarr[:,1:3]) # require all rows and only 2nd and 3rd columns
print('-'*55)
print(rarr[:-1,:]) # copy everything excluding last rows

[[0.2186756  0.74446207 0.82611307 0.55922726 0.6129722 ]
 [0.22710405 0.45958583 0.78929612 0.71918409 0.29055974]
 [0.44218903 0.03991683 0.85425051 0.07441108 0.57699401]
 [0.66283496 0.97714602 0.29556456 0.29318117 0.1849041 ]]
-------------------------------------------------------
[[0.2186756  0.74446207 0.82611307 0.55922726 0.6129722 ]
 [0.22710405 0.45958583 0.78929612 0.71918409 0.29055974]
 [0.44218903 0.03991683 0.85425051 0.07441108 0.57699401]
 [0.66283496 0.97714602 0.29556456 0.29318117 0.1849041 ]]
-------------------------------------------------------
[[0.22710405 0.45958583 0.78929612 0.71918409 0.29055974]
 [0.44218903 0.03991683 0.85425051 0.07441108 0.57699401]]
-------------------------------------------------------
[[0.74446207 0.82611307]
 [0.45958583 0.78929612]
 [0.03991683 0.85425051]
 [0.97714602 0.29556456]]
-------------------------------------------------------
[[0.2186756  0.74446207 0.82611307 0.55922726 0.6129722 ]
 [0.22710405 0.45958583 0.78929612